name: Deploy Server and Build App
on:
  push:
    branches:
      - master
      - ci

permissions:
  contents: write
  id-token: write

jobs:
  Deploy_Server_to_Cloud_Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: setup-env-vars
        name: Setup Environment Variables
        run: npm run setup:prod

      - id: auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
            create_credentials_file: true
            token_format: access_token
            workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
            service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      - id: login
        name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.GCP_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: build
        name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/pyxis/server:latest,
            ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/pyxis/server:${{ github.sha }}
          target: prod
          provenance: false

      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: pyxis
          image:  ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/pyxis/server:${{ github.sha }}
          env_vars_file: .env
          region: ${{ vars.GCP_REGION }}
          secrets: |-
            AUTH_SECRET=AUTH_SECRET:latest
            AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID:latest
            AWS_REGION=AWS_REGION:latest
            AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY:latest
            SUBSCRIPTION_REQUEST_SNS=SUBSCRIPTION_REQUEST_SNS:latest

  Build_App:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: install-deps
        name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.1 libsoup-3.0-dev javascriptcoregtk-4.1 -y

      - id: setup-pnpm
        name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - id: setup-rust-toolchain
        name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.83.0

      - id: setup-env-vars
        name: Setup Environment Variables
        run: pnpm setup:prod
    
      - id: install-cargo-workspaces
        name: Install Cargo Workspace
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-workspaces

      - id: update-crate-versions
        name: Update Crate Versions
        run: cargo workspaces version patch -y --no-git-commit

      - id: update-package-version
        name: Update Package Version
        run: pnpm version patch --no-git-tag-version

      - id: install-packages
        name: Install Packages
        run: pnpm install --frozen-lockfile

      - id: build-app
        name: Build App
        run: pnpm build:app

      - id: get_version
        name: Get version
        run: |
          VERSION=$(cargo pkgid -p pyxis-app | cut -d '#' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - id: upload-artifact
        name: Upload Release Artefact
        run: gh release create v${{ env.VERSION }} ./target/release/bundle/deb/pyxis_${{ env.VERSION }}_amd64.deb
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: commit-and-push
        name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'chore: bump package versions | [skip ci]'
          push: true
