name: Deploy Server and Build App
on:
  push:
    branches:
      - master
      - ci

permissions:
  contents: read
  id-token: write

jobs:
  Deploy_Server_to_Cloud_Run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - id: auth
      name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
          create_credentials_file: true
          token_format: access_token
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

    - id: login
      name: Login to GCR
      uses: docker/login-action@v3
      with:
        registry: europe-west2-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - id: buildx
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - id: build
      name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: europe-west2-docker.pkg.dev/${{ vars.GCP_PROJECT }}/pyxis/server:latest
        target: prod